on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  changelog:
    runs-on:
      - ubuntu-latest
    steps:
      - name: "âœï¸ ç”Ÿæˆå˜æ›´æ—¥å¿—"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  unit-test:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go mod tidy
      - run: go mod vendor
      - run: go test -v ./...
        name: "ğŸ å•å…ƒæµ‹è¯•"
        continue-on-error: true
  release:
    runs-on:
      - ubuntu-latest
    needs:
      - changelog
    steps:
      - name: "ğŸš„ å‘å¸ƒ release"
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          body: ${{needs.changelog.output.changelog}}
          fail_on_unmatched_files: false